### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Markus-bit** [mauro-balades/card-me#1]
your project does not work

**Comment by mauro-balades** [comment]
Did it work or does the problem still exist?

**Comment by Markus-bit** [comment]
When i type card after installing it gives an error message

**Comment by mauro-balades** [comment]
Could you please show me the error?

**Comment by Markus-bit** [comment]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/73933419/226195236-feb1792b-356d-459c-8024-5de47016cc1c.png">

**Comment by mauro-balades** [comment]
This is your problem, if you want to install a package globally, you will need to run it with `sudo` as the name suggests that npm does not have permission to access root files.

**Comment by Markus-bit** [comment]
ok sorry

**Comment by mauro-balades** [comment]
np 👍🏽
